### ISSUE TITLE
Send the model with the slug for enabling more customization on the revalidation

### ISSUE THREAD

**Issue by Mcastres** [DudiKaplan/strapi-plugin-revalidate-button#1]
We are using revalidation for the Strapi.io website and this plugin would be useful!
Unfortunately, we have some customization concerning what to revalidate depending on the model.

For now, the plugin only sends the slug, would it be possible to also send the model?

**Comment by DudiKaplan** [comment]
issue close

**Comment by DudiKaplan** [comment]
Thank you for the issue & PR, I merged the PR and now it is available in
the npm package 1.0.6

‫בתאריך יום ד׳, 9 באוג׳ 2023 ב-11:27 מאת ‪Maxime Castres‬‏ <‪
***@***.***‬‏>:‬
